name: Publish Plugin

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Gradle Plugin Portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Publish plugin
        run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
